databases:
  - name: dpg-c708pr1g7hp1bds8qeu0
    databaseName: dpg-c708pr1g7hp1bds8qeu0
    user: timetracker_user

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mylifetracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4