databases:
  - name: timetracker
    databaseName: timetracker
    user: timetracker_user

services:
  - type: web
    name: mytimetracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mylifetracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timetracker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4